### ISSUE TITLE
Factory Floorplan Transformations/Scaling

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/AndroidSQLClientServer#1]
We need to come up with how we're going to move the image over to each machine depending on which one gets returned from the server.

One option is to manually calibrate the Image View's [Matrix](https://developer.android.com/reference/android/widget/ImageView.html#setImageMatrix(android.graphics.Matrix)) so that we just have a set of 20-some hardcoded points that it just moves over to. It would be tedious, but so will basically any other implementation in one way or another.

**Comment by mackncheesiest** [comment]
May be replaced with hardcoding in images

**Comment by kcortez1** [comment]
Decided on hardcoding in images due to tedious nature of issue. CLOSED
